package com.github.unidbg.trace.text;

import com.github.unidbg.*;
import com.github.unidbg.arm.backend.Backend;
import java.io.PrintStream;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class DefaultSyscallParser implements TraceCallParser {

    private final Map<Long, String> syscallMap64 = new HashMap<>();
    private final Map<Long, String> syscallMap32 = new HashMap<>();
    private final Map<String, String[]> syscallArgs = new HashMap<>();

    public DefaultSyscallParser() {
        // === FULL ARM32 MAP ===
        syscallMap32.put(0L, "restart_syscall");
        syscallMap32.put(1L, "exit");
        syscallMap32.put(2L, "fork");
        syscallMap32.put(3L, "read");
        syscallMap32.put(4L, "write");
        syscallMap32.put(5L, "open");
        syscallMap32.put(6L, "close");
        syscallMap32.put(8L, "creat");
        syscallMap32.put(9L, "link");
        syscallMap32.put(10L, "unlink");
        syscallMap32.put(11L, "execve");
        syscallMap32.put(12L, "chdir");
        syscallMap32.put(14L, "mknod");
        syscallMap32.put(15L, "chmod");
        syscallMap32.put(16L, "lchown");
        syscallMap32.put(19L, "lseek");
        syscallMap32.put(20L, "getpid");
        syscallMap32.put(21L, "mount");
        syscallMap32.put(23L, "setuid");
        syscallMap32.put(24L, "getuid");
        syscallMap32.put(26L, "ptrace");
        syscallMap32.put(29L, "pause");
        syscallMap32.put(33L, "access");
        syscallMap32.put(34L, "nice");
        syscallMap32.put(36L, "sync");
        syscallMap32.put(37L, "kill");
        syscallMap32.put(38L, "rename");
        syscallMap32.put(39L, "mkdir");
        syscallMap32.put(40L, "rmdir");
        syscallMap32.put(41L, "dup");
        syscallMap32.put(42L, "pipe");
        syscallMap32.put(43L, "times");
        syscallMap32.put(45L, "brk");
        syscallMap32.put(46L, "setgid");
        syscallMap32.put(47L, "getgid");
        syscallMap32.put(49L, "geteuid");
        syscallMap32.put(50L, "getegid");
        syscallMap32.put(51L, "acct");
        syscallMap32.put(52L, "umount2");
        syscallMap32.put(54L, "ioctl");
        syscallMap32.put(55L, "fcntl");
        syscallMap32.put(57L, "setpgid");
        syscallMap32.put(60L, "umask");
        syscallMap32.put(61L, "chroot");
        syscallMap32.put(62L, "ustat");
        syscallMap32.put(63L, "dup2");
        syscallMap32.put(64L, "getppid");
        syscallMap32.put(65L, "getpgrp");
        syscallMap32.put(66L, "setsid");
        syscallMap32.put(67L, "sigaction");
        syscallMap32.put(70L, "setreuid");
        syscallMap32.put(71L, "setregid");
        syscallMap32.put(72L, "sigsuspend");
        syscallMap32.put(73L, "sigpending");
        syscallMap32.put(74L, "sethostname");
        syscallMap32.put(75L, "setrlimit");
        syscallMap32.put(77L, "getrusage");
        syscallMap32.put(78L, "gettimeofday");
        syscallMap32.put(79L, "settimeofday");
        syscallMap32.put(80L, "getgroups");
        syscallMap32.put(81L, "setgroups");
        syscallMap32.put(83L, "symlink");
        syscallMap32.put(85L, "readlink");
        syscallMap32.put(86L, "uselib");
        syscallMap32.put(87L, "swapon");
        syscallMap32.put(88L, "reboot");
        syscallMap32.put(91L, "munmap");
        syscallMap32.put(92L, "truncate");
        syscallMap32.put(93L, "ftruncate");
        syscallMap32.put(94L, "fchmod");
        syscallMap32.put(95L, "fchown");
        syscallMap32.put(96L, "getpriority");
        syscallMap32.put(97L, "setpriority");
        syscallMap32.put(99L, "statfs");
        syscallMap32.put(100L, "fstatfs");
        syscallMap32.put(103L, "syslog");
        syscallMap32.put(104L, "setitimer");
        syscallMap32.put(105L, "getitimer");
        syscallMap32.put(106L, "stat");
        syscallMap32.put(107L, "lstat");
        syscallMap32.put(108L, "fstat");
        syscallMap32.put(111L, "vhangup");
        syscallMap32.put(114L, "wait4");
        syscallMap32.put(115L, "swapoff");
        syscallMap32.put(116L, "sysinfo");
        syscallMap32.put(118L, "fsync");
        syscallMap32.put(119L, "sigreturn");
        syscallMap32.put(120L, "clone");
        syscallMap32.put(121L, "setdomainname");
        syscallMap32.put(122L, "uname");
        syscallMap32.put(124L, "adjtimex");
        syscallMap32.put(125L, "mprotect");
        syscallMap32.put(126L, "sigprocmask");
        syscallMap32.put(128L, "init_module");
        syscallMap32.put(129L, "delete_module");
        syscallMap32.put(131L, "quotactl");
        syscallMap32.put(132L, "getpgid");
        syscallMap32.put(133L, "fchdir");
        syscallMap32.put(134L, "bdflush");
        syscallMap32.put(135L, "sysfs");
        syscallMap32.put(136L, "personality");
        syscallMap32.put(138L, "setfsuid");
        syscallMap32.put(139L, "setfsgid");
        syscallMap32.put(140L, "_llseek");
        syscallMap32.put(141L, "getdents");
        syscallMap32.put(142L, "_newselect");
        syscallMap32.put(143L, "flock");
        syscallMap32.put(144L, "msync");
        syscallMap32.put(145L, "readv");
        syscallMap32.put(146L, "writev");
        syscallMap32.put(147L, "getsid");
        syscallMap32.put(148L, "fdatasync");
        syscallMap32.put(149L, "_sysctl");
        syscallMap32.put(150L, "mlock");
        syscallMap32.put(151L, "munlock");
        syscallMap32.put(152L, "mlockall");
        syscallMap32.put(153L, "munlockall");
        syscallMap32.put(154L, "sched_setparam");
        syscallMap32.put(155L, "sched_getparam");
        syscallMap32.put(156L, "sched_setscheduler");
        syscallMap32.put(157L, "sched_getscheduler");
        syscallMap32.put(158L, "sched_yield");
        syscallMap32.put(159L, "sched_get_priority_max");
        syscallMap32.put(160L, "sched_get_priority_min");
        syscallMap32.put(161L, "sched_rr_get_interval");
        syscallMap32.put(162L, "nanosleep");
        syscallMap32.put(163L, "mremap");
        syscallMap32.put(164L, "setresuid");
        syscallMap32.put(165L, "getresuid");
        syscallMap32.put(168L, "poll");
        syscallMap32.put(169L, "nfsservctl");
        syscallMap32.put(170L, "setresgid");
        syscallMap32.put(171L, "getresgid");
        syscallMap32.put(172L, "prctl");
        syscallMap32.put(173L, "rt_sigreturn");
        syscallMap32.put(174L, "rt_sigaction");
        syscallMap32.put(175L, "rt_sigprocmask");
        syscallMap32.put(176L, "rt_sigpending");
        syscallMap32.put(177L, "rt_sigtimedwait");
        syscallMap32.put(178L, "rt_sigqueueinfo");
        syscallMap32.put(179L, "rt_sigsuspend");
        syscallMap32.put(180L, "pread64");
        syscallMap32.put(181L, "pwrite64");
        syscallMap32.put(182L, "chown");
        syscallMap32.put(183L, "getcwd");
        syscallMap32.put(184L, "capget");
        syscallMap32.put(185L, "capset");
        syscallMap32.put(186L, "sigaltstack");
        syscallMap32.put(187L, "sendfile");
        syscallMap32.put(190L, "vfork");
        syscallMap32.put(191L, "ugetrlimit");
        syscallMap32.put(192L, "mmap2");
        syscallMap32.put(193L, "truncate64");
        syscallMap32.put(194L, "ftruncate64");
        syscallMap32.put(195L, "stat64");
        syscallMap32.put(196L, "lstat64");
        syscallMap32.put(197L, "fstat64");
        syscallMap32.put(198L, "lchown32");
        syscallMap32.put(199L, "getuid32");
        syscallMap32.put(200L, "getgid32");
        syscallMap32.put(201L, "geteuid32");
        syscallMap32.put(202L, "getegid32");
        syscallMap32.put(203L, "setreuid32");
        syscallMap32.put(204L, "setregid32");
        syscallMap32.put(205L, "getgroups32");
        syscallMap32.put(206L, "setgroups32");
        syscallMap32.put(207L, "fchown32");
        syscallMap32.put(208L, "setresuid32");
        syscallMap32.put(209L, "getresuid32");
        syscallMap32.put(210L, "setresgid32");
        syscallMap32.put(211L, "getresgid32");
        syscallMap32.put(212L, "chown32");
        syscallMap32.put(213L, "setuid32");
        syscallMap32.put(214L, "setgid32");
        syscallMap32.put(215L, "setfsuid32");
        syscallMap32.put(216L, "setfsgid32");
        syscallMap32.put(217L, "getdents64");
        syscallMap32.put(218L, "pivot_root");
        syscallMap32.put(219L, "mincore");
        syscallMap32.put(220L, "madvise");
        syscallMap32.put(221L, "fcntl64");
        syscallMap32.put(224L, "gettid");
        syscallMap32.put(225L, "readahead");
        syscallMap32.put(226L, "setxattr");
        syscallMap32.put(227L, "lsetxattr");
        syscallMap32.put(228L, "fsetxattr");
        syscallMap32.put(229L, "getxattr");
        syscallMap32.put(230L, "lgetxattr");
        syscallMap32.put(231L, "fgetxattr");
        syscallMap32.put(232L, "listxattr");
        syscallMap32.put(233L, "llistxattr");
        syscallMap32.put(234L, "flistxattr");
        syscallMap32.put(235L, "removexattr");
        syscallMap32.put(236L, "lremovexattr");
        syscallMap32.put(237L, "fremovexattr");
        syscallMap32.put(238L, "tkill");
        syscallMap32.put(239L, "sendfile64");
        syscallMap32.put(240L, "futex");
        syscallMap32.put(241L, "sched_setaffinity");
        syscallMap32.put(242L, "sched_getaffinity");
        syscallMap32.put(243L, "io_setup");
        syscallMap32.put(244L, "io_destroy");
        syscallMap32.put(245L, "io_getevents");
        syscallMap32.put(246L, "io_submit");
        syscallMap32.put(247L, "io_cancel");
        syscallMap32.put(248L, "exit_group");
        syscallMap32.put(249L, "lookup_dcookie");
        syscallMap32.put(250L, "epoll_create");
        syscallMap32.put(251L, "epoll_ctl");
        syscallMap32.put(252L, "epoll_wait");
        syscallMap32.put(253L, "remap_file_pages");
        syscallMap32.put(256L, "set_tid_address");
        syscallMap32.put(257L, "timer_create");
        syscallMap32.put(258L, "timer_settime");
        syscallMap32.put(259L, "timer_gettime");
        syscallMap32.put(260L, "timer_getoverrun");
        syscallMap32.put(261L, "timer_delete");
        syscallMap32.put(262L, "clock_settime");
        syscallMap32.put(263L, "clock_gettime");
        syscallMap32.put(264L, "clock_getres");
        syscallMap32.put(265L, "clock_nanosleep");
        syscallMap32.put(266L, "statfs64");
        syscallMap32.put(267L, "fstatfs64");
        syscallMap32.put(268L, "tgkill");
        syscallMap32.put(269L, "utimes");
        syscallMap32.put(270L, "arm_fadvise64_64");
        syscallMap32.put(271L, "pciconfig_iobase");
        syscallMap32.put(272L, "pciconfig_read");
        syscallMap32.put(273L, "pciconfig_write");
        syscallMap32.put(274L, "mq_open");
        syscallMap32.put(275L, "mq_unlink");
        syscallMap32.put(276L, "mq_timedsend");
        syscallMap32.put(277L, "mq_timedreceive");
        syscallMap32.put(278L, "mq_notify");
        syscallMap32.put(279L, "mq_getsetattr");
        syscallMap32.put(280L, "waitid");
        syscallMap32.put(281L, "socket");
        syscallMap32.put(282L, "bind");
        syscallMap32.put(283L, "connect");
        syscallMap32.put(284L, "listen");
        syscallMap32.put(285L, "accept");
        syscallMap32.put(286L, "getsockname");
        syscallMap32.put(287L, "getpeername");
        syscallMap32.put(288L, "socketpair");
        syscallMap32.put(289L, "send");
        syscallMap32.put(290L, "sendto");
        syscallMap32.put(291L, "recv");
        syscallMap32.put(292L, "recvfrom");
        syscallMap32.put(293L, "shutdown");
        syscallMap32.put(294L, "setsockopt");
        syscallMap32.put(295L, "getsockopt");
        syscallMap32.put(296L, "sendmsg");
        syscallMap32.put(297L, "recvmsg");
        syscallMap32.put(298L, "semop");
        syscallMap32.put(299L, "semget");
        syscallMap32.put(300L, "semctl");
        syscallMap32.put(301L, "msgsnd");
        syscallMap32.put(302L, "msgrcv");
        syscallMap32.put(303L, "msgget");
        syscallMap32.put(304L, "msgctl");
        syscallMap32.put(305L, "shmat");
        syscallMap32.put(306L, "shmdt");
        syscallMap32.put(307L, "shmget");
        syscallMap32.put(308L, "shmctl");
        syscallMap32.put(309L, "add_key");
        syscallMap32.put(310L, "request_key");
        syscallMap32.put(311L, "keyctl");
        syscallMap32.put(312L, "semtimedop");
        syscallMap32.put(313L, "vserver");
        syscallMap32.put(314L, "ioprio_set");
        syscallMap32.put(315L, "ioprio_get");
        syscallMap32.put(316L, "inotify_init");
        syscallMap32.put(317L, "inotify_add_watch");
        syscallMap32.put(318L, "inotify_rm_watch");
        syscallMap32.put(319L, "mbind");
        syscallMap32.put(320L, "get_mempolicy");
        syscallMap32.put(321L, "set_mempolicy");
        syscallMap32.put(322L, "openat");
        syscallMap32.put(323L, "mkdirat");
        syscallMap32.put(324L, "mknodat");
        syscallMap32.put(325L, "fchownat");
        syscallMap32.put(326L, "futimesat");
        syscallMap32.put(327L, "fstatat64");
        syscallMap32.put(328L, "unlinkat");
        syscallMap32.put(329L, "renameat");
        syscallMap32.put(330L, "linkat");
        syscallMap32.put(331L, "symlinkat");
        syscallMap32.put(332L, "readlinkat");
        syscallMap32.put(333L, "fchmodat");
        syscallMap32.put(334L, "faccessat");
        syscallMap32.put(335L, "pselect6");
        syscallMap32.put(336L, "ppoll");
        syscallMap32.put(337L, "unshare");
        syscallMap32.put(338L, "set_robust_list");
        syscallMap32.put(339L, "get_robust_list");
        syscallMap32.put(340L, "splice");
        syscallMap32.put(341L, "arm_sync_file_range");
        syscallMap32.put(341L, "sync_file_range2");
        syscallMap32.put(342L, "tee");
        syscallMap32.put(343L, "vmsplice");
        syscallMap32.put(344L, "move_pages");
        syscallMap32.put(345L, "getcpu");
        syscallMap32.put(346L, "epoll_pwait");
        syscallMap32.put(347L, "kexec_load");
        syscallMap32.put(348L, "utimensat");
        syscallMap32.put(349L, "signalfd");
        syscallMap32.put(350L, "timerfd_create");
        syscallMap32.put(351L, "eventfd");
        syscallMap32.put(352L, "fallocate");
        syscallMap32.put(353L, "timerfd_settime");
        syscallMap32.put(354L, "timerfd_gettime");
        syscallMap32.put(355L, "signalfd4");
        syscallMap32.put(356L, "eventfd2");
        syscallMap32.put(357L, "epoll_create1");
        syscallMap32.put(358L, "dup3");
        syscallMap32.put(359L, "pipe2");
        syscallMap32.put(360L, "inotify_init1");
        syscallMap32.put(361L, "preadv");
        syscallMap32.put(362L, "pwritev");
        syscallMap32.put(363L, "rt_tgsigqueueinfo");
        syscallMap32.put(364L, "perf_event_open");
        syscallMap32.put(365L, "recvmmsg");
        syscallMap32.put(366L, "accept4");
        syscallMap32.put(367L, "fanotify_init");
        syscallMap32.put(368L, "fanotify_mark");
        syscallMap32.put(369L, "prlimit64");
        syscallMap32.put(370L, "name_to_handle_at");
        syscallMap32.put(371L, "open_by_handle_at");
        syscallMap32.put(372L, "clock_adjtime");
        syscallMap32.put(373L, "syncfs");
        syscallMap32.put(374L, "sendmmsg");
        syscallMap32.put(375L, "setns");
        syscallMap32.put(376L, "process_vm_readv");
        syscallMap32.put(377L, "process_vm_writev");
        syscallMap32.put(378L, "kcmp");
        syscallMap32.put(379L, "finit_module");
        syscallMap32.put(380L, "sched_setattr");
        syscallMap32.put(381L, "sched_getattr");
        syscallMap32.put(382L, "renameat2");
        syscallMap32.put(383L, "seccomp");
        syscallMap32.put(384L, "getrandom");
        syscallMap32.put(385L, "memfd_create");
        syscallMap32.put(386L, "bpf");
        syscallMap32.put(387L, "execveat");
        syscallMap32.put(388L, "userfaultfd");
        syscallMap32.put(389L, "membarrier");
        syscallMap32.put(390L, "mlock2");
        syscallMap32.put(391L, "copy_file_range");
        syscallMap32.put(392L, "preadv2");
        syscallMap32.put(393L, "pwritev2");
        syscallMap32.put(394L, "pkey_mprotect");
        syscallMap32.put(395L, "pkey_alloc");
        syscallMap32.put(396L, "pkey_free");
        syscallMap32.put(397L, "statx");
        syscallMap32.put(983041L, "ARM_breakpoint");
        syscallMap32.put(983042L, "ARM_cacheflush");
        syscallMap32.put(983043L, "ARM_usr26");
        syscallMap32.put(983044L, "ARM_usr32");
        syscallMap32.put(983045L, "ARM_set_tls");

        // === INIT MAP ===
        syscallMap64.put(0L, "io_setup");
        syscallMap64.put(1L, "io_destroy");
        syscallMap64.put(2L, "io_submit");
        syscallMap64.put(3L, "io_cancel");
        syscallMap64.put(4L, "io_getevents");
        syscallMap64.put(5L, "setxattr");
        syscallMap64.put(6L, "lsetxattr");
        syscallMap64.put(7L, "fsetxattr");
        syscallMap64.put(8L, "getxattr");
        syscallMap64.put(9L, "lgetxattr");
        syscallMap64.put(10L, "fgetxattr");
        syscallMap64.put(11L, "listxattr");
        syscallMap64.put(12L, "llistxattr");
        syscallMap64.put(13L, "flistxattr");
        syscallMap64.put(14L, "removexattr");
        syscallMap64.put(15L, "lremovexattr");
        syscallMap64.put(16L, "fremovexattr");
        syscallMap64.put(17L, "getcwd");
        syscallMap64.put(18L, "lookup_dcookie");
        syscallMap64.put(19L, "eventfd2");
        syscallMap64.put(20L, "epoll_create1");
        syscallMap64.put(21L, "epoll_ctl");
        syscallMap64.put(22L, "epoll_pwait");
        syscallMap64.put(23L, "dup");
        syscallMap64.put(24L, "dup3");
        syscallMap64.put(25L, "fcntl");
        syscallMap64.put(26L, "inotify_init1");
        syscallMap64.put(27L, "inotify_add_watch");
        syscallMap64.put(28L, "inotify_rm_watch");
        syscallMap64.put(29L, "ioctl");
        syscallMap64.put(30L, "ioprio_set");
        syscallMap64.put(31L, "ioprio_get");
        syscallMap64.put(32L, "flock");
        syscallMap64.put(33L, "mknodat");
        syscallMap64.put(34L, "mkdirat");
        syscallMap64.put(35L, "unlinkat");
        syscallMap64.put(36L, "symlinkat");
        syscallMap64.put(37L, "linkat");
        syscallMap64.put(38L, "renameat");
        syscallMap64.put(39L, "umount2");
        syscallMap64.put(40L, "mount");
        syscallMap64.put(41L, "pivot_root");
        syscallMap64.put(42L, "nfsservctl");
        syscallMap64.put(43L, "statfs");
        syscallMap64.put(44L, "fstatfs");
        syscallMap64.put(45L, "truncate");
        syscallMap64.put(46L, "ftruncate");
        syscallMap64.put(47L, "fallocate");
        syscallMap64.put(48L, "faccessat");
        syscallMap64.put(49L, "chdir");
        syscallMap64.put(50L, "fchdir");
        syscallMap64.put(51L, "chroot");
        syscallMap64.put(52L, "fchmod");
        syscallMap64.put(53L, "fchmodat");
        syscallMap64.put(54L, "fchownat");
        syscallMap64.put(55L, "fchown");
        syscallMap64.put(56L, "openat");
        syscallMap64.put(57L, "close");
        syscallMap64.put(58L, "vhangup");
        syscallMap64.put(59L, "pipe2");
        syscallMap64.put(60L, "quotactl");
        syscallMap64.put(61L, "getdents64");
        syscallMap64.put(62L, "lseek");
        syscallMap64.put(63L, "read");
        syscallMap64.put(64L, "write");
        syscallMap64.put(65L, "readv");
        syscallMap64.put(66L, "writev");
        syscallMap64.put(67L, "pread64");
        syscallMap64.put(68L, "pwrite64");
        syscallMap64.put(69L, "preadv");
        syscallMap64.put(70L, "pwritev");
        syscallMap64.put(71L, "sendfile");
        syscallMap64.put(72L, "pselect6");
        syscallMap64.put(73L, "ppoll");
        syscallMap64.put(74L, "signalfd4");
        syscallMap64.put(75L, "vmsplice");
        syscallMap64.put(76L, "splice");
        syscallMap64.put(77L, "tee");
        syscallMap64.put(78L, "readlinkat");
        syscallMap64.put(79L, "newfstatat");
        syscallMap64.put(80L, "fstat");
        syscallMap64.put(81L, "sync");
        syscallMap64.put(82L, "fsync");
        syscallMap64.put(83L, "fdatasync");
        syscallMap64.put(84L, "sync_file_range");
        syscallMap64.put(85L, "timerfd_create");
        syscallMap64.put(86L, "timerfd_settime");
        syscallMap64.put(87L, "timerfd_gettime");
        syscallMap64.put(88L, "utimensat");
        syscallMap64.put(89L, "acct");
        syscallMap64.put(90L, "capget");
        syscallMap64.put(91L, "capset");
        syscallMap64.put(92L, "personality");
        syscallMap64.put(93L, "exit");
        syscallMap64.put(94L, "exit_group");
        syscallMap64.put(95L, "waitid");
        syscallMap64.put(96L, "set_tid_address");
        syscallMap64.put(97L, "unshare");
        syscallMap64.put(98L, "futex");
        syscallMap64.put(99L, "set_robust_list");
        syscallMap64.put(100L, "get_robust_list");
        syscallMap64.put(101L, "nanosleep");
        syscallMap64.put(102L, "getitimer");
        syscallMap64.put(103L, "setitimer");
        syscallMap64.put(104L, "kexec_load");
        syscallMap64.put(105L, "init_module");
        syscallMap64.put(106L, "delete_module");
        syscallMap64.put(107L, "timer_create");
        syscallMap64.put(108L, "timer_gettime");
        syscallMap64.put(109L, "timer_getoverrun");
        syscallMap64.put(110L, "timer_settime");
        syscallMap64.put(111L, "timer_delete");
        syscallMap64.put(112L, "clock_settime");
        syscallMap64.put(113L, "clock_gettime");
        syscallMap64.put(114L, "clock_getres");
        syscallMap64.put(115L, "clock_nanosleep");
        syscallMap64.put(116L, "syslog");
        syscallMap64.put(117L, "ptrace");
        syscallMap64.put(118L, "sched_setparam");
        syscallMap64.put(119L, "sched_setscheduler");
        syscallMap64.put(120L, "sched_getscheduler");
        syscallMap64.put(121L, "sched_getparam");
        syscallMap64.put(122L, "sched_setaffinity");
        syscallMap64.put(123L, "sched_getaffinity");
        syscallMap64.put(124L, "sched_yield");
        syscallMap64.put(125L, "sched_get_priority_max");
        syscallMap64.put(126L, "sched_get_priority_min");
        syscallMap64.put(127L, "sched_rr_get_interval");
        syscallMap64.put(128L, "restart_syscall");
        syscallMap64.put(129L, "kill");
        syscallMap64.put(130L, "tkill");
        syscallMap64.put(131L, "tgkill");
        syscallMap64.put(132L, "sigaltstack");
        syscallMap64.put(133L, "rt_sigsuspend");
        syscallMap64.put(134L, "rt_sigaction");
        syscallMap64.put(135L, "rt_sigprocmask");
        syscallMap64.put(136L, "rt_sigpending");
        syscallMap64.put(137L, "rt_sigtimedwait");
        syscallMap64.put(138L, "rt_sigqueueinfo");
        syscallMap64.put(139L, "rt_sigreturn");
        syscallMap64.put(140L, "setpriority");
        syscallMap64.put(141L, "getpriority");
        syscallMap64.put(142L, "reboot");
        syscallMap64.put(143L, "setregid");
        syscallMap64.put(144L, "setgid");
        syscallMap64.put(145L, "setreuid");
        syscallMap64.put(146L, "setuid");
        syscallMap64.put(147L, "setresuid");
        syscallMap64.put(148L, "getresuid");
        syscallMap64.put(149L, "setresgid");
        syscallMap64.put(150L, "getresgid");
        syscallMap64.put(151L, "setfsuid");
        syscallMap64.put(152L, "setfsgid");
        syscallMap64.put(153L, "times");
        syscallMap64.put(154L, "setpgid");
        syscallMap64.put(155L, "getpgid");
        syscallMap64.put(156L, "getsid");
        syscallMap64.put(157L, "setsid");
        syscallMap64.put(158L, "getgroups");
        syscallMap64.put(159L, "setgroups");
        syscallMap64.put(160L, "uname");
        syscallMap64.put(161L, "sethostname");
        syscallMap64.put(162L, "setdomainname");
        syscallMap64.put(163L, "getrlimit");
        syscallMap64.put(164L, "setrlimit");
        syscallMap64.put(165L, "getrusage");
        syscallMap64.put(166L, "umask");
        syscallMap64.put(167L, "prctl");
        syscallMap64.put(168L, "getcpu");
        syscallMap64.put(169L, "gettimeofday");
        syscallMap64.put(170L, "settimeofday");
        syscallMap64.put(171L, "adjtimex");
        syscallMap64.put(172L, "getpid");
        syscallMap64.put(173L, "getppid");
        syscallMap64.put(174L, "getuid");
        syscallMap64.put(175L, "geteuid");
        syscallMap64.put(176L, "getgid");
        syscallMap64.put(177L, "getegid");
        syscallMap64.put(178L, "gettid");
        syscallMap64.put(179L, "sysinfo");
        syscallMap64.put(180L, "mq_open");
        syscallMap64.put(181L, "mq_unlink");
        syscallMap64.put(182L, "mq_timedsend");
        syscallMap64.put(183L, "mq_timedreceive");
        syscallMap64.put(184L, "mq_notify");
        syscallMap64.put(185L, "mq_getsetattr");
        syscallMap64.put(186L, "msgget");
        syscallMap64.put(187L, "msgctl");
        syscallMap64.put(188L, "msgrcv");
        syscallMap64.put(189L, "msgsnd");
        syscallMap64.put(190L, "semget");
        syscallMap64.put(191L, "semctl");
        syscallMap64.put(192L, "semtimedop");
        syscallMap64.put(193L, "semop");
        syscallMap64.put(194L, "shmget");
        syscallMap64.put(195L, "shmctl");
        syscallMap64.put(196L, "shmat");
        syscallMap64.put(197L, "shmdt");
        syscallMap64.put(198L, "socket");
        syscallMap64.put(199L, "socketpair");
        syscallMap64.put(200L, "bind");
        syscallMap64.put(201L, "listen");
        syscallMap64.put(202L, "accept");
        syscallMap64.put(203L, "connect");
        syscallMap64.put(204L, "getsockname");
        syscallMap64.put(205L, "getpeername");
        syscallMap64.put(206L, "sendto");
        syscallMap64.put(207L, "recvfrom");
        syscallMap64.put(208L, "setsockopt");
        syscallMap64.put(209L, "getsockopt");
        syscallMap64.put(210L, "shutdown");
        syscallMap64.put(211L, "sendmsg");
        syscallMap64.put(212L, "recvmsg");
        syscallMap64.put(213L, "readahead");
        syscallMap64.put(214L, "brk");
        syscallMap64.put(215L, "munmap");
        syscallMap64.put(216L, "mremap");
        syscallMap64.put(217L, "add_key");
        syscallMap64.put(218L, "request_key");
        syscallMap64.put(219L, "keyctl");
        syscallMap64.put(220L, "clone");
        syscallMap64.put(221L, "execve");
        syscallMap64.put(222L, "mmap");
        syscallMap64.put(223L, "fadvise64");
        syscallMap64.put(224L, "swapon");
        syscallMap64.put(225L, "swapoff");
        syscallMap64.put(226L, "mprotect");
        syscallMap64.put(227L, "msync");
        syscallMap64.put(228L, "mlock");
        syscallMap64.put(229L, "munlock");
        syscallMap64.put(230L, "mlockall");
        syscallMap64.put(231L, "munlockall");
        syscallMap64.put(232L, "mincore");
        syscallMap64.put(233L, "madvise");
        syscallMap64.put(234L, "remap_file_pages");
        syscallMap64.put(235L, "mbind");
        syscallMap64.put(236L, "get_mempolicy");
        syscallMap64.put(237L, "set_mempolicy");
        syscallMap64.put(238L, "migrate_pages");
        syscallMap64.put(239L, "move_pages");
        syscallMap64.put(240L, "rt_tgsigqueueinfo");
        syscallMap64.put(241L, "perf_event_open");
        syscallMap64.put(242L, "accept4");
        syscallMap64.put(243L, "recvmmsg");
        syscallMap64.put(260L, "wait4");
        syscallMap64.put(261L, "prlimit64");
        syscallMap64.put(262L, "fanotify_init");
        syscallMap64.put(263L, "fanotify_mark");
        syscallMap64.put(264L, "name_to_handle_at");
        syscallMap64.put(265L, "open_by_handle_at");
        syscallMap64.put(266L, "clock_adjtime");
        syscallMap64.put(267L, "syncfs");
        syscallMap64.put(268L, "setns");
        syscallMap64.put(269L, "sendmmsg");
        syscallMap64.put(270L, "process_vm_readv");
        syscallMap64.put(271L, "process_vm_writev");
        syscallMap64.put(272L, "kcmp");
        syscallMap64.put(273L, "finit_module");
        syscallMap64.put(274L, "sched_setattr");
        syscallMap64.put(275L, "sched_getattr");
        syscallMap64.put(276L, "renameat2");
        syscallMap64.put(277L, "seccomp");
        syscallMap64.put(278L, "getrandom");
        syscallMap64.put(279L, "memfd_create");
        syscallMap64.put(280L, "bpf");
        syscallMap64.put(281L, "execveat");
        syscallMap64.put(282L, "userfaultfd");
        syscallMap64.put(283L, "membarrier");
        syscallMap64.put(284L, "mlock2");
        syscallMap64.put(285L, "copy_file_range");
        syscallMap64.put(286L, "preadv2");
        syscallMap64.put(287L, "pwritev2");
        syscallMap64.put(288L, "pkey_mprotect");
        syscallMap64.put(289L, "pkey_alloc");
        syscallMap64.put(290L, "pkey_free");
        syscallMap64.put(291L, "statx");

        // === INIT ARGS ===
        syscallArgs.put("io_setup", new String[] { "nr_reqs:int", "ctx:ptr" });
        syscallArgs.put("io_destroy", new String[] { "ctx:int" });
        syscallArgs.put("io_submit", new String[] { "aio_context_t:int", "long:int", "arg:ptr" });
        syscallArgs.put("io_cancel", new String[] { "ctx_id:int", "iocb:ptr", "result:ptr" });
        syscallArgs.put("io_getevents", new String[] { "ctx_id:int", "min_nr:int", "nr:int", "events:ptr", "timeout:ptr" });
        syscallArgs.put("setxattr", new String[] { "path:str", "name:str", "value:ptr", "size:size", "flags:int" });
        syscallArgs.put("lsetxattr", new String[] { "path:str", "name:str", "value:ptr", "size:size", "flags:int" });
        syscallArgs.put("fsetxattr", new String[] { "fd:int", "name:str", "value:ptr", "size:size", "flags:int" });
        syscallArgs.put("getxattr", new String[] { "path:str", "name:str", "value:ptr", "size:size" });
        syscallArgs.put("lgetxattr", new String[] { "path:str", "name:str", "value:ptr", "size:size" });
        syscallArgs.put("fgetxattr", new String[] { "fd:int", "name:str", "value:ptr", "size:size" });
        syscallArgs.put("listxattr", new String[] { "path:str", "list:str", "size:size" });
        syscallArgs.put("llistxattr", new String[] { "path:str", "list:str", "size:size" });
        syscallArgs.put("flistxattr", new String[] { "fd:int", "list:str", "size:size" });
        syscallArgs.put("removexattr", new String[] { "path:str", "name:str" });
        syscallArgs.put("lremovexattr", new String[] { "path:str", "name:str" });
        syscallArgs.put("fremovexattr", new String[] { "fd:int", "name:str" });
        syscallArgs.put("getcwd", new String[] { "buf:str", "size:size" });
        syscallArgs.put("lookup_dcookie", new String[] { "cookie64:int", "buf:str", "len:size" });
        syscallArgs.put("eventfd2", new String[] { "count:size", "flags:int" });
        syscallArgs.put("epoll_create1", new String[] { "flags:int" });
        syscallArgs.put("epoll_ctl", new String[] { "epfd:int", "op:int", "fd:int", "event:ptr" });
        syscallArgs.put("epoll_pwait", new String[] { "epfd:int", "events:ptr", "maxevents:int", "timeout:int", "sigmask:ptr", "sigsetsize:size" });
        syscallArgs.put("dup", new String[] { "fildes:int" });
        syscallArgs.put("dup3", new String[] { "oldfd:int", "newfd:int", "flags:int" });
        syscallArgs.put("fcntl", new String[] { "fd:int", "cmd:int", "arg:size" });
        syscallArgs.put("inotify_init1", new String[] { "flags:int" });
        syscallArgs.put("inotify_add_watch", new String[] { "fd:int", "path:str", "mask:int" });
        syscallArgs.put("inotify_rm_watch", new String[] { "fd:int", "wd:int" });
        syscallArgs.put("ioctl", new String[] { "fd:int", "cmd:int", "arg:size" });
        syscallArgs.put("ioprio_set", new String[] { "which:int", "who:int", "ioprio:int" });
        syscallArgs.put("ioprio_get", new String[] { "which:int", "who:int" });
        syscallArgs.put("flock", new String[] { "fd:int", "cmd:int" });
        syscallArgs.put("mknodat", new String[] { "dfd:int", "filename:str", "mode:int", "dev:int" });
        syscallArgs.put("mkdirat", new String[] { "dfd:int", "pathname:str", "mode:int" });
        syscallArgs.put("unlinkat", new String[] { "dfd:int", "pathname:str", "flag:int" });
        syscallArgs.put("symlinkat", new String[] { "oldname:str", "newdfd:int", "newname:str" });
        syscallArgs.put("linkat", new String[] { "olddfd:int", "oldname:str", "newdfd:int", "newname:str", "flags:int" });
        syscallArgs.put("renameat", new String[] { "olddfd:int", "oldname:str", "newdfd:int", "newname:str" });
        syscallArgs.put("umount2", new String[0]);
        syscallArgs.put("mount", new String[] { "dev_name:str", "dir_name:str", "type:str", "flags:size", "data:ptr" });
        syscallArgs.put("pivot_root", new String[] { "new_root:str", "put_old:str" });
        syscallArgs.put("nfsservctl", new String[0]);
        syscallArgs.put("statfs", new String[] { "path:str", "buf:ptr" });
        syscallArgs.put("fstatfs", new String[] { "fd:int", "buf:ptr" });
        syscallArgs.put("truncate", new String[] { "path:str", "length:size" });
        syscallArgs.put("ftruncate", new String[] { "fd:int", "length:size" });
        syscallArgs.put("fallocate", new String[] { "fd:int", "mode:int", "offset:size", "len:size" });
        syscallArgs.put("faccessat", new String[] { "dfd:int", "filename:str", "mode:int" });
        syscallArgs.put("chdir", new String[] { "filename:str" });
        syscallArgs.put("fchdir", new String[] { "fd:int" });
        syscallArgs.put("chroot", new String[] { "filename:str" });
        syscallArgs.put("fchmod", new String[] { "fd:int", "mode:int" });
        syscallArgs.put("fchmodat", new String[] { "dfd:int", "filename:str", "mode:int" });
        syscallArgs.put("fchownat", new String[] { "dfd:int", "filename:str", "user:int", "group:int", "flag:int" });
        syscallArgs.put("fchown", new String[] { "fd:int", "user:int", "group:int" });
        syscallArgs.put("openat", new String[] { "dfd:int", "filename:str", "flags:int", "mode:int" });
        syscallArgs.put("close", new String[] { "fd:int" });
        syscallArgs.put("vhangup", new String[0]);
        syscallArgs.put("pipe2", new String[] { "fildes:ptr", "flags:int" });
        syscallArgs.put("quotactl", new String[] { "cmd:int", "special:str", "id:int", "addr:ptr" });
        syscallArgs.put("getdents64", new String[] { "fd:int", "dirent:ptr", "count:size" });
        syscallArgs.put("lseek", new String[] { "fd:int", "offset:int", "whence:int" });
        syscallArgs.put("read", new String[] { "fd:int", "buf:str", "count:size" });
        syscallArgs.put("write", new String[] { "fd:int", "buf:str", "count:size" });
        syscallArgs.put("readv", new String[] { "fd:size", "vec:ptr", "vlen:size" });
        syscallArgs.put("writev", new String[] { "fd:size", "vec:ptr", "vlen:size" });
        syscallArgs.put("pread64", new String[] { "fd:int", "buf:str", "count:size", "pos:size" });
        syscallArgs.put("pwrite64", new String[] { "fd:int", "buf:str", "count:size", "pos:size" });
        syscallArgs.put("preadv", new String[] { "fd:size", "vec:ptr", "vlen:size", "pos_l:size", "pos_h:size" });
        syscallArgs.put("pwritev", new String[] { "fd:size", "vec:ptr", "vlen:size", "pos_l:size", "pos_h:size" });
        syscallArgs.put("sendfile", new String[] { "out_fd:int", "in_fd:int", "offset:ptr", "count:size" });
        syscallArgs.put("pselect6", new String[] { "int:int", "arg:ptr", "arg:ptr", "arg:ptr", "arg:ptr", "arg:ptr" });
        syscallArgs.put("ppoll", new String[] { "arg:ptr", "int:int", "arg:ptr", "arg:ptr", "size_t:size" });
        syscallArgs.put("signalfd4", new String[] { "ufd:int", "user_mask:ptr", "sizemask:size", "flags:int" });
        syscallArgs.put("vmsplice", new String[] { "fd:int", "iov:ptr", "nr_segs:size", "flags:int" });
        syscallArgs.put("splice", new String[] { "fd_in:int", "off_in:ptr", "fd_out:int", "off_out:ptr", "len:size", "flags:int" });
        syscallArgs.put("tee", new String[] { "fdin:int", "fdout:int", "len:size", "flags:int" });
        syscallArgs.put("readlinkat", new String[] { "dfd:int", "path:str", "buf:str", "bufsiz:ptr" });
        syscallArgs.put("newfstatat", new String[] { "dfd:int", "filename:str", "statbuf:ptr", "flag:int" });
        syscallArgs.put("fstat", new String[] { "fd:int", "statbuf:ptr" });
        syscallArgs.put("sync", new String[0]);
        syscallArgs.put("fsync", new String[] { "fd:int" });
        syscallArgs.put("fdatasync", new String[] { "fd:int" });
        syscallArgs.put("sync_file_range", new String[] { "fd:int", "offset:size", "nbytes:size", "flags:int" });
        syscallArgs.put("timerfd_create", new String[] { "clockid:int", "flags:int" });
        syscallArgs.put("timerfd_settime", new String[] { "ufd:int", "flags:int", "utmr:ptr", "otmr:ptr" });
        syscallArgs.put("timerfd_gettime", new String[] { "ufd:int", "otmr:ptr" });
        syscallArgs.put("utimensat", new String[] { "dfd:int", "filename:str", "utimes:ptr", "flags:int" });
        syscallArgs.put("acct", new String[] { "name:str" });
        syscallArgs.put("capget", new String[] { "header:int", "dataptr:int" });
        syscallArgs.put("capset", new String[] { "header:int", "data:int" });
        syscallArgs.put("personality", new String[] { "personality:int" });
        syscallArgs.put("exit", new String[] { "error_code:int" });
        syscallArgs.put("exit_group", new String[] { "error_code:int" });
        syscallArgs.put("waitid", new String[] { "which:int", "pid:int", "infop:ptr", "options:int", "ru:ptr" });
        syscallArgs.put("set_tid_address", new String[] { "tidptr:ptr" });
        syscallArgs.put("unshare", new String[] { "unshare_flags:size" });
        syscallArgs.put("futex", new String[] { "uaddr:ptr", "op:int", "val:int", "utime:ptr", "uaddr2:ptr", "val3:int" });
        syscallArgs.put("set_robust_list", new String[] { "head:ptr", "len:size" });
        syscallArgs.put("get_robust_list", new String[] { "pid:int", "head_ptr:ptr", "len_ptr:ptr" });
        syscallArgs.put("nanosleep", new String[] { "rqtp:ptr", "rmtp:ptr" });
        syscallArgs.put("getitimer", new String[] { "which:int", "value:ptr" });
        syscallArgs.put("setitimer", new String[] { "which:int", "value:ptr", "ovalue:ptr" });
        syscallArgs.put("kexec_load", new String[] { "entry:size", "nr_segments:size", "segments:ptr", "flags:size" });
        syscallArgs.put("init_module", new String[] { "umod:ptr", "len:size", "uargs:str" });
        syscallArgs.put("delete_module", new String[] { "name_user:str", "flags:int" });
        syscallArgs.put("timer_create", new String[] { "which_clock:int", "timer_event_spec:ptr", "created_timer_id:ptr" });
        syscallArgs.put("timer_gettime", new String[] { "timer_id:int", "setting:ptr" });
        syscallArgs.put("timer_getoverrun", new String[] { "timer_id:int" });
        syscallArgs.put("timer_settime", new String[] { "timer_id:int", "flags:int", "new_setting:ptr", "old_setting:ptr" });
        syscallArgs.put("timer_delete", new String[] { "timer_id:int" });
        syscallArgs.put("clock_settime", new String[] { "which_clock:int", "tp:ptr" });
        syscallArgs.put("clock_gettime", new String[] { "which_clock:int", "tp:ptr" });
        syscallArgs.put("clock_getres", new String[] { "which_clock:int", "tp:ptr" });
        syscallArgs.put("clock_nanosleep", new String[] { "which_clock:int", "flags:int", "rqtp:ptr", "rmtp:ptr" });
        syscallArgs.put("syslog", new String[] { "type:int", "buf:str", "len:size" });
        syscallArgs.put("ptrace", new String[] { "request:int", "pid:int", "addr:size", "data:size" });
        syscallArgs.put("sched_setparam", new String[] { "pid:int", "param:ptr" });
        syscallArgs.put("sched_setscheduler", new String[] { "pid:int", "policy:int", "param:ptr" });
        syscallArgs.put("sched_getscheduler", new String[] { "pid:int" });
        syscallArgs.put("sched_getparam", new String[] { "pid:int", "param:ptr" });
        syscallArgs.put("sched_setaffinity", new String[] { "pid:int", "len:size", "user_mask_ptr:ptr" });
        syscallArgs.put("sched_getaffinity", new String[] { "pid:int", "len:size", "user_mask_ptr:ptr" });
        syscallArgs.put("sched_yield", new String[0]);
        syscallArgs.put("sched_get_priority_max", new String[] { "policy:int" });
        syscallArgs.put("sched_get_priority_min", new String[] { "policy:int" });
        syscallArgs.put("sched_rr_get_interval", new String[] { "pid:int", "interval:ptr" });
        syscallArgs.put("restart_syscall", new String[0]);
        syscallArgs.put("kill", new String[] { "pid:int", "sig:int" });
        syscallArgs.put("tkill", new String[] { "pid:int", "sig:int" });
        syscallArgs.put("tgkill", new String[] { "tgid:int", "pid:int", "sig:int" });
        syscallArgs.put("sigaltstack", new String[] { "uss:ptr", "uoss:ptr" });
        syscallArgs.put("rt_sigsuspend", new String[] { "unewset:ptr", "sigsetsize:size" });
        syscallArgs.put("rt_sigaction", new String[] { "int:int", "arg:ptr", "arg:ptr", "size_t:size" });
        syscallArgs.put("rt_sigprocmask", new String[] { "how:int", "set:ptr", "oset:ptr", "sigsetsize:size" });
        syscallArgs.put("rt_sigpending", new String[] { "set:ptr", "sigsetsize:size" });
        syscallArgs.put("rt_sigtimedwait", new String[] { "uthese:ptr", "uinfo:ptr", "uts:ptr", "sigsetsize:size" });
        syscallArgs.put("rt_sigqueueinfo", new String[] { "pid:int", "sig:int", "uinfo:ptr" });
        syscallArgs.put("rt_sigreturn", new String[0]);
        syscallArgs.put("setpriority", new String[] { "which:int", "who:int", "niceval:int" });
        syscallArgs.put("getpriority", new String[] { "which:int", "who:int" });
        syscallArgs.put("reboot", new String[] { "magic1:int", "magic2:int", "cmd:int", "arg:ptr" });
        syscallArgs.put("setregid", new String[] { "rgid:int", "egid:int" });
        syscallArgs.put("setgid", new String[] { "gid:int" });
        syscallArgs.put("setreuid", new String[] { "ruid:int", "euid:int" });
        syscallArgs.put("setuid", new String[] { "uid:int" });
        syscallArgs.put("setresuid", new String[] { "ruid:int", "euid:int", "suid:int" });
        syscallArgs.put("getresuid", new String[] { "ruid:ptr", "euid:ptr", "suid:ptr" });
        syscallArgs.put("setresgid", new String[] { "rgid:int", "egid:int", "sgid:int" });
        syscallArgs.put("getresgid", new String[] { "rgid:ptr", "egid:ptr", "sgid:ptr" });
        syscallArgs.put("setfsuid", new String[] { "uid:int" });
        syscallArgs.put("setfsgid", new String[] { "gid:int" });
        syscallArgs.put("times", new String[] { "tbuf:ptr" });
        syscallArgs.put("setpgid", new String[] { "pid:int", "pgid:int" });
        syscallArgs.put("getpgid", new String[] { "pid:int" });
        syscallArgs.put("getsid", new String[] { "pid:int" });
        syscallArgs.put("setsid", new String[0]);
        syscallArgs.put("getgroups", new String[] { "gidsetsize:int", "grouplist:ptr" });
        syscallArgs.put("setgroups", new String[] { "gidsetsize:int", "grouplist:ptr" });
        syscallArgs.put("uname", new String[] { "arg:ptr" });
        syscallArgs.put("sethostname", new String[] { "name:str", "len:size" });
        syscallArgs.put("setdomainname", new String[] { "name:str", "len:size" });
        syscallArgs.put("getrlimit", new String[] { "resource:int", "rlim:ptr" });
        syscallArgs.put("setrlimit", new String[] { "resource:int", "rlim:ptr" });
        syscallArgs.put("getrusage", new String[] { "who:int", "ru:ptr" });
        syscallArgs.put("umask", new String[] { "mask:int" });
        syscallArgs.put("prctl", new String[] { "option:int", "arg2:size", "arg3:size", "arg4:size", "arg5:size" });
        syscallArgs.put("getcpu", new String[] { "cpu:ptr", "node:ptr", "cache:ptr" });
        syscallArgs.put("gettimeofday", new String[] { "tv:ptr", "tz:ptr" });
        syscallArgs.put("settimeofday", new String[] { "tv:ptr", "tz:ptr" });
        syscallArgs.put("adjtimex", new String[] { "txc_p:ptr" });
        syscallArgs.put("getpid", new String[0]);
        syscallArgs.put("getppid", new String[0]);
        syscallArgs.put("getuid", new String[0]);
        syscallArgs.put("geteuid", new String[0]);
        syscallArgs.put("getgid", new String[0]);
        syscallArgs.put("getegid", new String[0]);
        syscallArgs.put("gettid", new String[0]);
        syscallArgs.put("sysinfo", new String[] { "info:ptr" });
        syscallArgs.put("mq_open", new String[] { "name:str", "oflag:int", "mode:int", "attr:ptr" });
        syscallArgs.put("mq_unlink", new String[] { "name:str" });
        syscallArgs.put("mq_timedsend", new String[] { "mqdes:int", "msg_ptr:str", "msg_len:size", "msg_prio:int", "abs_timeout:ptr" });
        syscallArgs.put("mq_timedreceive", new String[] { "mqdes:int", "msg_ptr:str", "msg_len:size", "msg_prio:ptr", "abs_timeout:ptr" });
        syscallArgs.put("mq_notify", new String[] { "mqdes:int", "notification:ptr" });
        syscallArgs.put("mq_getsetattr", new String[] { "mqdes:int", "mqstat:ptr", "omqstat:ptr" });
        syscallArgs.put("msgget", new String[] { "key:int", "msgflg:int" });
        syscallArgs.put("msgctl", new String[] { "msqid:int", "cmd:int", "buf:ptr" });
        syscallArgs.put("msgrcv", new String[] { "msqid:int", "msgp:ptr", "msgsz:size", "msgtyp:int", "msgflg:int" });
        syscallArgs.put("msgsnd", new String[] { "msqid:int", "msgp:ptr", "msgsz:size", "msgflg:int" });
        syscallArgs.put("semget", new String[] { "key:int", "nsems:int", "semflg:int" });
        syscallArgs.put("semctl", new String[] { "semid:int", "semnum:int", "cmd:int", "arg:size" });
        syscallArgs.put("semtimedop", new String[] { "semid:int", "sops:ptr", "nsops:int", "timeout:ptr" });
        syscallArgs.put("semop", new String[] { "semid:int", "sops:ptr", "nsops:int" });
        syscallArgs.put("shmget", new String[] { "key:int", "size:size", "flag:int" });
        syscallArgs.put("shmctl", new String[] { "shmid:int", "cmd:int", "buf:ptr" });
        syscallArgs.put("shmat", new String[] { "shmid:int", "shmaddr:str", "shmflg:int" });
        syscallArgs.put("shmdt", new String[] { "shmaddr:str" });
        syscallArgs.put("socket", new String[] { "int:int", "int:int", "int:int" });
        syscallArgs.put("socketpair", new String[] { "int:int", "int:int", "int:int", "arg:ptr" });
        syscallArgs.put("bind", new String[] { "int:int", "arg:ptr", "int:int" });
        syscallArgs.put("listen", new String[] { "int:int", "int:int" });
        syscallArgs.put("accept", new String[] { "int:int", "arg:ptr", "arg:ptr" });
        syscallArgs.put("connect", new String[] { "int:int", "arg:ptr", "int:int" });
        syscallArgs.put("getsockname", new String[] { "int:int", "arg:ptr", "arg:ptr" });
        syscallArgs.put("getpeername", new String[] { "int:int", "arg:ptr", "arg:ptr" });
        syscallArgs.put("sendto", new String[] { "int:int", "arg:ptr", "size_t:size", "unsigned:int", "arg:ptr", "int:int" });
        syscallArgs.put("recvfrom", new String[] { "int:int", "arg:ptr", "size_t:size", "unsigned:int", "arg:ptr", "arg:ptr" });
        syscallArgs.put("setsockopt", new String[] { "fd:int", "level:int", "optname:int", "optval:str", "optlen:size" });
        syscallArgs.put("getsockopt", new String[] { "fd:int", "level:int", "optname:int", "optval:str", "optlen:ptr" });
        syscallArgs.put("shutdown", new String[] { "int:int", "int:int" });
        syscallArgs.put("sendmsg", new String[] { "fd:int", "msg:ptr", "flags:int" });
        syscallArgs.put("recvmsg", new String[] { "fd:int", "msg:ptr", "flags:int" });
        syscallArgs.put("readahead", new String[] { "fd:int", "offset:size", "count:size" });
        syscallArgs.put("brk", new String[] { "brk:size" });
        syscallArgs.put("munmap", new String[] { "addr:size", "len:size" });
        syscallArgs.put("mremap", new String[] { "addr:size", "old_len:size", "new_len:size", "flags:size", "new_addr:size" });
        syscallArgs.put("add_key", new String[] { "_type:str", "_description:str", "_payload:ptr", "plen:size", "destringid:int" });
        syscallArgs.put("request_key", new String[] { "_type:str", "_description:str", "_callout_info:str", "destringid:int" });
        syscallArgs.put("keyctl", new String[] { "cmd:int", "arg2:size", "arg3:size", "arg4:size", "arg5:size" });
        syscallArgs.put("clone", new String[] { "long:size", "long:size", "arg:ptr", "arg:ptr", "long:size" });
        syscallArgs.put("execve", new String[] { "filename:str", "argv:str", "envp:str" });
        syscallArgs.put("mmap", new String[0]);
        syscallArgs.put("fadvise64", new String[] { "fd:int", "offset:size", "len:size", "advice:int" });
        syscallArgs.put("swapon", new String[] { "specialfile:str", "swap_flags:int" });
        syscallArgs.put("swapoff", new String[] { "specialfile:str" });
        syscallArgs.put("mprotect", new String[] { "start:size", "len:size", "prot:size" });
        syscallArgs.put("msync", new String[] { "start:size", "len:size", "flags:int" });
        syscallArgs.put("mlock", new String[] { "start:size", "len:size" });
        syscallArgs.put("munlock", new String[] { "start:size", "len:size" });
        syscallArgs.put("mlockall", new String[] { "flags:int" });
        syscallArgs.put("munlockall", new String[0]);
        syscallArgs.put("mincore", new String[] { "start:size", "len:size", "vec:str" });
        syscallArgs.put("madvise", new String[] { "start:size", "len:size", "behavior:int" });
        syscallArgs.put("remap_file_pages", new String[] { "start:size", "size:size", "prot:size", "pgoff:size", "flags:size" });
        syscallArgs.put("mbind", new String[] { "start:size", "len:size", "mode:size", "nmask:ptr", "maxnode:size", "flags:int" });
        syscallArgs.put("get_mempolicy", new String[] { "policy:ptr", "nmask:ptr", "maxnode:size", "addr:size", "flags:size" });
        syscallArgs.put("set_mempolicy", new String[] { "mode:int", "nmask:ptr", "maxnode:size" });
        syscallArgs.put("migrate_pages", new String[] { "pid:int", "maxnode:size", "from:ptr", "to:ptr" });
        syscallArgs.put("move_pages", new String[] { "pid:int", "nr_pages:size", "pages:ptr", "nodes:ptr", "status:ptr", "flags:int" });
        syscallArgs.put("rt_tgsigqueueinfo", new String[] { "tgid:int", "pid:int", "sig:int", "uinfo:ptr" });
        syscallArgs.put("perf_event_open", new String[] { "attr_uptr:ptr", "pid:int", "cpu:int", "group_fd:int", "flags:size" });
        syscallArgs.put("accept4", new String[] { "int:int", "arg:ptr", "arg:ptr", "int:int" });
        syscallArgs.put("recvmmsg", new String[] { "fd:int", "msg:ptr", "vlen:size", "flags:int", "timeout:ptr" });
        syscallArgs.put("wait4", new String[] { "pid:int", "stat_addr:ptr", "options:int", "ru:ptr" });
        syscallArgs.put("prlimit64", new String[] { "pid:int", "resource:int", "new_rlim:ptr", "old_rlim:ptr" });
        syscallArgs.put("fanotify_init", new String[] { "flags:int", "event_f_flags:int" });
        syscallArgs.put("fanotify_mark", new String[] { "fanotify_fd:int", "flags:int", "mask:int", "fd:int", "pathname:str" });
        syscallArgs.put("name_to_handle_at", new String[] { "dfd:int", "name:str", "handle:ptr", "mnt_id:ptr", "flag:int" });
        syscallArgs.put("open_by_handle_at", new String[] { "mountdirfd:int", "handle:ptr", "flags:int" });
        syscallArgs.put("clock_adjtime", new String[] { "which_clock:int", "tx:ptr" });
        syscallArgs.put("syncfs", new String[] { "fd:int" });
        syscallArgs.put("setns", new String[] { "fd:int", "nstype:int" });
        syscallArgs.put("sendmmsg", new String[] { "fd:int", "msg:ptr", "vlen:size", "flags:int" });
        syscallArgs.put("process_vm_readv", new String[] { "pid:int", "lvec:ptr", "liovcnt:size", "rvec:ptr", "riovcnt:size", "flags:size" });
        syscallArgs.put("process_vm_writev", new String[] { "pid:int", "lvec:ptr", "liovcnt:size", "rvec:ptr", "riovcnt:size", "flags:size" });
        syscallArgs.put("kcmp", new String[] { "pid1:int", "pid2:int", "type:int", "idx1:size", "idx2:size" });
        syscallArgs.put("finit_module", new String[] { "fd:int", "uargs:str", "flags:int" });
        syscallArgs.put("sched_setattr", new String[] { "pid:int", "attr:ptr", "flags:int" });
        syscallArgs.put("sched_getattr", new String[] { "pid:int", "attr:ptr", "size:int", "flags:int" });
        syscallArgs.put("renameat2", new String[] { "olddfd:int", "oldname:str", "newdfd:int", "newname:str", "flags:int" });
        syscallArgs.put("seccomp", new String[] { "op:int", "flags:int", "uargs:ptr" });
        syscallArgs.put("getrandom", new String[] { "buf:str", "count:size", "flags:int" });
        syscallArgs.put("memfd_create", new String[] { "uname_ptr:str", "flags:int" });
        syscallArgs.put("bpf", new String[] { "cmd:int", "attr:ptr", "size:int" });
        syscallArgs.put("execveat", new String[] { "dfd:int", "filename:str", "argv:str", "envp:str", "flags:int" });
        syscallArgs.put("userfaultfd", new String[] { "flags:int" });
        syscallArgs.put("membarrier", new String[] { "cmd:int", "flags:int" });
        syscallArgs.put("mlock2", new String[] { "start:size", "len:size", "flags:int" });
        syscallArgs.put("copy_file_range", new String[] { "fd_in:int", "off_in:ptr", "fd_out:int", "off_out:ptr", "len:size", "flags:int" });
        syscallArgs.put("preadv2", new String[] { "fd:size", "vec:ptr", "vlen:size", "pos_l:size", "pos_h:size", "flags:int" });
        syscallArgs.put("pwritev2", new String[] { "fd:size", "vec:ptr", "vlen:size", "pos_l:size", "pos_h:size", "flags:int" });
        syscallArgs.put("pkey_mprotect", new String[] { "start:size", "len:size", "prot:size", "pkey:int" });
        syscallArgs.put("pkey_alloc", new String[] { "flags:size", "init_val:size" });
        syscallArgs.put("pkey_free", new String[] { "pkey:int" });
        syscallArgs.put("statx", new String[] { "dfd:int", "path:str", "flags:int", "mask:int", "buffer:ptr" });
        syscallArgs.put("read", new String[] { "fd:int", "buf:ptr", "count:size" });
        // === ARM32 SPECIFIC ARGS ===
        syscallArgs.put("fork", new String[0]);
        syscallArgs.put("open", new String[] { "filename:str", "flags:int", "mode:int" });
        syscallArgs.put("creat", new String[] { "pathname:str", "mode:int" });
        syscallArgs.put("link", new String[] { "oldname:str", "newname:str" });
        syscallArgs.put("unlink", new String[] { "pathname:str" });
        syscallArgs.put("mknod", new String[] { "filename:str", "mode:int", "dev:int" });
        syscallArgs.put("chmod", new String[] { "filename:str", "mode:int" });
        syscallArgs.put("lchown", new String[] { "filename:str", "user:int", "group:int" });
        syscallArgs.put("pause", new String[0]);
        syscallArgs.put("access", new String[] { "filename:str", "mode:int" });
        syscallArgs.put("nice", new String[] { "increment:int" });
        syscallArgs.put("rename", new String[] { "oldname:str", "newname:str" });
        syscallArgs.put("mkdir", new String[] { "pathname:str", "mode:int" });
        syscallArgs.put("rmdir", new String[] { "pathname:str" });
        syscallArgs.put("pipe", new String[] { "fildes:ptr" });
        syscallArgs.put("ustat", new String[] { "dev:int", "ubuf:ptr" });
        syscallArgs.put("dup2", new String[] { "oldfd:int", "newfd:int" });
        syscallArgs.put("getpgrp", new String[0]);
        syscallArgs.put("sigaction", new String[] { "int:int", "arg:ptr", "arg:ptr" });
        syscallArgs.put("sigsuspend", new String[] { "unused1:int", "unused2:int", "mask:int" });
        syscallArgs.put("sigpending", new String[] { "uset:ptr" });
        syscallArgs.put("symlink", new String[] { "old:str", "new:str" });
        syscallArgs.put("readlink", new String[] { "path:str", "buf:str", "bufsiz:ptr" });
        syscallArgs.put("uselib", new String[] { "library:str" });
        syscallArgs.put("stat", new String[] { "filename:str", "statbuf:ptr" });
        syscallArgs.put("lstat", new String[] { "filename:str", "statbuf:ptr" });
        syscallArgs.put("sigreturn", new String[0]);
        syscallArgs.put("sigprocmask", new String[] { "how:int", "set:ptr", "oset:ptr" });
        syscallArgs.put("bdflush", new String[] { "func:int", "data:int" });
        syscallArgs.put("sysfs", new String[] { "option:int", "arg1:size", "arg2:size" });
        syscallArgs.put("_llseek", new String[0]);
        syscallArgs.put("getdents", new String[] { "fd:int", "dirent:ptr", "count:size" });
        syscallArgs.put("_newselect", new String[0]);
        syscallArgs.put("_sysctl", new String[0]);
        syscallArgs.put("poll", new String[] { "ufds:ptr", "nfds:int", "timeout:int" });
        syscallArgs.put("chown", new String[] { "filename:str", "user:int", "group:int" });
        syscallArgs.put("vfork", new String[0]);
        syscallArgs.put("ugetrlimit", new String[0]);
        syscallArgs.put("mmap2", new String[0]);
        syscallArgs.put("truncate64", new String[] { "path:str", "length:size" });
        syscallArgs.put("ftruncate64", new String[] { "fd:int", "length:size" });
        syscallArgs.put("stat64", new String[] { "filename:str", "statbuf:ptr" });
        syscallArgs.put("lstat64", new String[] { "filename:str", "statbuf:ptr" });
        syscallArgs.put("fstat64", new String[] { "fd:size", "statbuf:ptr" });
        syscallArgs.put("lchown32", new String[0]);
        syscallArgs.put("getuid32", new String[0]);
        syscallArgs.put("getgid32", new String[0]);
        syscallArgs.put("geteuid32", new String[0]);
        syscallArgs.put("getegid32", new String[0]);
        syscallArgs.put("setreuid32", new String[0]);
        syscallArgs.put("setregid32", new String[0]);
        syscallArgs.put("getgroups32", new String[0]);
        syscallArgs.put("setgroups32", new String[0]);
        syscallArgs.put("fchown32", new String[0]);
        syscallArgs.put("setresuid32", new String[0]);
        syscallArgs.put("getresuid32", new String[0]);
        syscallArgs.put("setresgid32", new String[0]);
        syscallArgs.put("getresgid32", new String[0]);
        syscallArgs.put("chown32", new String[0]);
        syscallArgs.put("setuid32", new String[0]);
        syscallArgs.put("setgid32", new String[0]);
        syscallArgs.put("setfsuid32", new String[0]);
        syscallArgs.put("setfsgid32", new String[0]);
        syscallArgs.put("fcntl64", new String[] { "fd:int", "cmd:int", "arg:size" });
        syscallArgs.put("sendfile64", new String[] { "out_fd:int", "in_fd:int", "offset:ptr", "count:size" });
        syscallArgs.put("epoll_create", new String[] { "size:int" });
        syscallArgs.put("epoll_wait", new String[] { "epfd:int", "events:ptr", "maxevents:int", "timeout:int" });
        syscallArgs.put("statfs64", new String[] { "path:str", "sz:size", "buf:ptr" });
        syscallArgs.put("fstatfs64", new String[] { "fd:int", "sz:size", "buf:ptr" });
        syscallArgs.put("utimes", new String[] { "filename:str", "utimes:ptr" });
        syscallArgs.put("arm_fadvise64_64", new String[0]);
        syscallArgs.put("pciconfig_iobase", new String[] { "which:int", "bus:size", "devfn:size" });
        syscallArgs.put("pciconfig_read", new String[] { "bus:size", "dfn:size", "off:size", "len:size", "buf:ptr" });
        syscallArgs.put("pciconfig_write", new String[] { "bus:size", "dfn:size", "off:size", "len:size", "buf:ptr" });
        syscallArgs.put("send", new String[] { "int:int", "arg:ptr", "size_t:size", "unsigned:int" });
        syscallArgs.put("recv", new String[] { "int:int", "arg:ptr", "size_t:size", "unsigned:int" });
        syscallArgs.put("vserver", new String[0]);
        syscallArgs.put("inotify_init", new String[0]);
        syscallArgs.put("futimesat", new String[] { "dfd:int", "filename:str", "utimes:ptr" });
        syscallArgs.put("fstatat64", new String[] { "dfd:int", "filename:str", "statbuf:ptr", "flag:int" });
        syscallArgs.put("arm_sync_file_range", new String[0]);
        syscallArgs.put("sync_file_range2", new String[] { "fd:int", "flags:int", "offset:size", "nbytes:size" });
        syscallArgs.put("signalfd", new String[] { "ufd:int", "user_mask:ptr", "sizemask:size" });
        syscallArgs.put("eventfd", new String[] { "count:size" });
        syscallArgs.put("ARM_breakpoint", new String[0]);
        syscallArgs.put("ARM_cacheflush", new String[0]);
        syscallArgs.put("ARM_usr26", new String[0]);
        syscallArgs.put("ARM_usr32", new String[0]);
        syscallArgs.put("ARM_set_tls", new String[0]);
        syscallArgs.put("write", new String[] { "fd:int", "buf:ptr", "count:size" });
    }

    @Override
    public boolean canHandle(String moduleName, String symbolName, boolean isJni) {
        return "syscall".equals(moduleName) || (symbolName != null && symbolName.startsWith("syscall_"));
    }

    @Override
    public String formatCall(AssemblyCodeTextDumper.PendingCall call, Backend backend, boolean is64Bit, Emulator<?> emulator, AssemblyCodeTextDumper dumper) {
        String syscallName = call.funcName;
        if (syscallName.startsWith("syscall_")) {
            long syscallNum = Long.parseLong(syscallName.substring(8));
            String mappedName = is64Bit ? syscallMap64.get(syscallNum) : syscallMap32.get(syscallNum);
            if (mappedName != null) syscallName = mappedName;
            call.funcName = syscallName; // Upgrade the pending call internally
        }

        String[] argsTypes = syscallArgs.get(syscallName);
        StringBuilder sb = new StringBuilder("svc ").append(syscallName).append("(");
        String formatStr = null;

        if (argsTypes != null) {
            for (int i = 0; i < argsTypes.length; i++) {
                if (i > 0) sb.append(", ");
                String[] parts = argsTypes[i].split(":");
                String name = parts[0];
                String type = parts[1];
                
                long arg = dumper.getArgRegValue(backend, i, is64Bit);
                sb.append(dumper.formatArgValue(type, arg, backend));
                
                if ("format".equals(name) && "str".equals(type)) {
                    formatStr = dumper.readStringSafe(backend, arg);
                }
            }
            
            if (formatStr != null && (syscallName.contains("write") || syscallName.contains("syslog"))) {
                List<String> specifiers = dumper.extractFormatSpecifiers(formatStr);
                int argIndex = argsTypes.length;
                for (String spec : specifiers) {
                    sb.append(", ");
                    long arg = dumper.getArgRegValue(backend, argIndex++, is64Bit);
                    if (spec.endsWith("s")) {
                        sb.append(dumper.formatArgValue("str", arg, backend));
                    } else if (spec.endsWith("c")) {
                        sb.append(dumper.formatArgValue("char", arg, backend));
                    } else if (spec.endsWith("p")) {
                        sb.append(dumper.formatArgValue("ptr", arg, backend));
                    } else {
                        sb.append(arg).append(" (0x").append(Long.toHexString(arg)).append(")");
                    }
                }
            }
        } else {
            sb.append("...");
        }
        sb.append(")");
        return sb.toString();
    }

    @Override
    public String formatReturnValue(AssemblyCodeTextDumper.PendingCall call, long retVal, Backend backend, boolean is64Bit, Emulator<?> emulator, AssemblyCodeTextDumper dumper) {
        if (retVal >= -1000 && retVal <= 1000) {
            return String.valueOf(retVal) + " (0x" + Long.toHexString(retVal) + ")";
        }
        return "0x" + Long.toHexString(retVal);
    }

    @Override
    public void printPostReturnMemoryDump(PrintStream out, AssemblyCodeTextDumper.PendingCall call, long retVal, Backend backend, boolean is64Bit, Emulator<?> emulator, AssemblyCodeTextDumper dumper) {
        // Syscall generally does not have complex post-memory dumps mapped standardly here,
        // unless you want to parse 'read' syscall destination buffer
    }
}
